### ISSUE TITLE
More advanced activation functions.

### ISSUE THREAD

**Issue by WuZhuoran** [ddbourgin/numpy-ml#7]
- [x] ReLU
- [x] Tanh
- [x] Affine
- [x] Sigmoid
- [x] Leaky ReLU
- [x] ELU
- [x] Linear
- [x] Softmax
- [x] Hard Sigmoid
- [x] Exponential
- [ ] PReLU
- [ ] ThresholdedReLU
- [x] SELU
- [ ] Softplus
- [ ] Softsign

I will try to implement rest part of activation functions. Any better ideas for activation function?

**Comment by kmario23** [comment]
@WuZhuoran Great! I think it's also worth looking into [Activation_function#Comparison_of_activation_functions](https://en.wikipedia.org/wiki/Activation_function#Comparison_of_activation_functions)

**Comment by ddbourgin** [comment]
Awesome! Two quick notes:
- `Linear` is just a special case of `Affine` (with slope=1, intercept=0), so no need to implement a separate function
- `Softmax` actually already exists, but as a Layer rather than an activation function. I decided to do this because it is much more efficient to calculate the gradient through the activation and projection weights together rather than in sequence. 

Otherwise, looks good! I'll have a look at your PR when I have a spare moment :)

**Comment by WuZhuoran** [comment]
@ddbourgin Cool.
Fixed. 

I will commit after you review the code. About the `NumPy Style Python Docstrings`, I will update ASAP.
